import re

# http://www1.nyc.gov/assets/dsny/js/agencies/dispose_data_stg.js

dispose_data = []
for i in range(180):
	dispose_data.append([])
dispose_data[0] = ["3-ring binders","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Discard as garbage on regular collection day(s). Can recycle the metal parts with metal, glass, plastic, & cartons.","3-ring binders,ring binder,ring binders,three-ring binder,three ring binder,three-ring binders,three ring binders,3 ring binder"];
dispose_data[1] = ["aerosol can (empty)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic, & cartons","aerosol can (empty),can,cans,spray cans,whip cream,whipped cream,empty cans,hair spray,aerosol can,empty aerosol can,aerosol cans,spray deoderant can,spray sunscreen can"];
dispose_data[2] = ["aluminum","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons","aluminum,aluminum products,aluminum foil,foil,tin foil,tin,tray,trays,pan,aluminum bottle,aluminum bottles,metal bottles,aluminum pots and pans"];
dispose_data[3] = ["antifreeze","/assets/dsny/zerowaste/residents/antifreeze.shtml","learn more","Never drain antifreeze onto the street, and do not dispose down the drain, in sewers, or into streams. Have your antifreeze changed by a professional who offers recycling. Antifreeze can also be taken to upcoming DSNY SAFE disposal events. Otherwise, dry out antifreeze using kitty litter, newspaper, or other absorbent material prior to discarding in the garbage. Empty antifreeze containers can be recycled with other metal, glass, plastic & cartons.","antifreeze,coolant"];
dispose_data[4] = ["appliance containing CFC/Freon","/assets/dsny/zerowaste/residents/appliances.shtml","learn more","Donate or sell working appliances. Otherwise make appointment with DSNY to remove CFCs and recycle the metal. For safety reasons, you must remove doors prior to set out.","appliance containing CFC/Freon,appliances,cfc,cfcs,freon,coolant,cooling,air conditioner,air conditioning unit,A/C,AC,dehumidifier,freezer,freezers,icebox,fridge,refrigerator,refrigerators,water cooler,water coolers,wine chiller,appliance"];
dispose_data[5] = ["art supplies","/assets/dsny/zerowaste/residents/art-supplies.shtml","learn more","Donate or sell; recycle clean paper, empty and recycle metal, plastic and glass containers; all other material, discard as garbage on regular collection day(s)","art supplies,art,supplies,craft supplies,craft paper"];
dispose_data[6] = ["asbestos","/assets/dsny/zerowaste/residents/asbestos.shtml","learn more","Asbestos should never be disposed of at the curb. Contact an appropriate private hazardous/chemical waste company.","asbestos"];
dispose_data[7] = ["auto battery","/assets/dsny/zerowaste/residents/auto-batteries.shtml","learn more","It is illegal to discard a car battery in the garbage or recycling or on the street. Auto batteries can be recycled at service stations or auto supply stores that sell them, or take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","auto battery,auto batteries,automotive,battery (auto),automotive battery,automotive batteries,car,cars,car battery,car batteries,auto battery,lead-acid battery,lead-acid batteries,vehicle battery,vehicle batteries"];
dispose_data[8] = ["backup battery","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Illegal to discard in garbage or recycling if less than 25 lbs. Recycle through a retailer or manufacturer take-back program or take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","backup battery,battery (backup),batteries (backup),backup,backup battery,backup batteries,UPS battery,UPS batteries,uninterruptable power supply"];
dispose_data[9] = ["barbecue grill","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Remove propane tank and set out as bulk metal next to recycling container on your recycling collection day. Propane tanks can't be discarded at the curb. Exchange empty propane tank for a full tank at any local propane tank dealer. If not exchanging your tank, ask dealer to recycle, or bring to a scrap metal dealer. Propane tanks can be taken to upcoming DSNY SAFE Disposal Events.","barbecue grill,barbecue grills,barbecue,grill,grills,bbq,gas appliance,barbecue propane gas tank,gas cylinder,helium tank,helium balloon tank"];
dispose_data[10] = ["battery (alkaline)","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Discard alkaline batteries in the garbage (they aren't hazardous since they no longer contain mercury) or take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","battery (alkaline),batteries,battery,alkaline,alkaline batteries,alkaline battery,household batteries"];
dispose_data[11] = ["battery (rechargeable)","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Illegal to discard with garbage or recycling. Stores in NY State that sell rechargeable batteries or products that contain them (with the exception of small food stores) must accept up to ten batteries of the same shape and size that they sell or take to household special waste drop-off site or upcoming DSNY SAFE disposal event. Individually bag batteries or tape terminals prior to dropping off.","battery (rechargeable),rechargeable,batteries,battery,rechargable,Ni-cad battery,Ni-cad batteries,nickel cadmium battery,nickel cadmium batteries,NiMH battery,NiMH batteries,Nickel metal hydride battery,Nickel metal hydride batteries,li-ion battery,li-ion batteries,lithium ion battery,lithium ion batteries,small-sealed lead-acid battery,small-sealed lead-acid batteries,button battery,"];
dispose_data[12] = ["bed frame (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Set out next to your recycling container on your recycling collection day. Fully wrap mattresses and box springs within a sealed plastic bag (to prevent spread of bed bugs)","bed frame (mostly metal or rigid plastic),futon,futon frame,bed rail,bed,bed frame"];
dispose_data[13] = ["bed frame (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Remove mattress and box spring. Discard as bulk garbage on regular collection day(s). Fully wrap mattresses and box springs within a sealed plastic bag (to prevent spread of bed bugs)","bed frame (not mostly metal or rigid plastic),futon,futon frame,bed rail,bed,bed frame"];
dispose_data[14] = ["beer bottle/can","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with other metal, glass, plastic & cartons, or return to store for refund if there is a deposit on the container.","beer bottle/can,beer bottle,beer bottles,beer can,beer cans,metal bottle,deposit bottle/can,deposit container,deposit containers,deposit bottle,deposit can,deposit bottles,deposit cans"];
dispose_data[15] = ["bioplastics","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic, & cartons. Do not place these items in home composting bins, even if they say compostable. Compostable plastics can only be composted in industrial-scale facilities designed to handle such material.","bioplastics,biodegradeable plastic,compostable plastic,bio-based plastic,plastic compostable,plastic biodegradable,plastic bio-based"];
dispose_data[16] = ["blanket","/assets/dsny/zerowaste/residents/textiles.shtml","learn more","Donate or sell; or discard as garbage on regular collection day(s).","blanket,blankets"];
dispose_data[17] = ["book (hard cover)","/assets/dsny/zerowaste/residents/books-and-media.shtml","learn more","Donate or sell if in good condition. Otherwise discard as non-recyclable garbage on regular collection day(s); do not place in recycling bin.","book (hard cover),books,hard cover book,hard cover books,hardcover,text book,textbook,,text books,textbooks"];
dispose_data[18] = ["book (paperback)","/assets/dsny/zerowaste/residents/books-and-media.shtml","learn more","Donate or sell if in good condition. Otherwise, recycle with mixed paper and cardboard.","book (paperback),paperback book,paperback books,soft cover book,soft cover books,coloring book,coloring books,comic book,comic books"];
dispose_data[19] = ["box spring","/assets/dsny/zerowaste/residents/furniture.shtml","learn more","Must fully enclose within a sealed plastic bag (to prevent spread of bed bugs) and discard as bulk garbage on regular collection day(s). (Beds cannot be donated.)","box spring,box,spring,springs,boxspring,bed"];
dispose_data[20] = ["branches/tree limbs (do-it-yourself)","/assets/dsny/zerowaste/residents/yard-waste.shtml","learn more","Sanitation can't collect firewood and wood from trees growing on residential properties in Brooklyn and Queens due to Asian Longhorned Beetle infestation. Schedule an appointment with Parks & Recreation for free on-site chipping and disposal in designated areas. All other areas can discard this material as bulk garbage on regular collection days (it can be collected separately in organics collection pilot areas). Branches must be bundled 2 feet by 4 feet or smaller.","branches/tree limbs (do-it-yourself),branches,tree,trees,limb,limbs,firewood,tree limbs,tree branches,wood debris,yard waste"];
dispose_data[21] = ["branches/tree limbs (hired professional)","/assets/dsny/zerowaste/residents/yard-waste.shtml","learn more","Branches generated by hired professionals can't be set out for curbside collection. Professionals must dispose of branches they generate at a permitted composting facility. This includes proper disposal of wood from trees within Asian Longhorned Beetle quarantine zones.","branches/tree limbs (hired professional),branches,tree,limb,firewood,tree limbs,tree branches,wood debris,professional tree removal,yard waste"];
dispose_data[22] = ["broken fluorescent light","/assets/dsny/zerowaste/residents/lighting.shtml","learn more","Contains minimal amounts of mercury. The EPA recommends as a best practice that you air out the room with a window or door; collect materials with cardboard, tape, or wet paper; and place into a sealable container. Turn off air conditioning or heating unit if possible. Can be taken to upcoming DSNY SAFE disposal events. Can also be legally discarded in garbage, but double bag for safety.","broken fluorescent light,broken fluorescent bulb,broken fluorescent bulbs,broken CFL,broken CFLs,broken fluorescent lamp,broken compact fluorescent lamp,broken compact fluorescent lamps"];
dispose_data[23] = ["bulk (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Set out bulk metal and bulk plastic next to your recycling container on your recycling collection day. For appliances containing CFCs, you must schedule an appointment to place item at the curb for CFC recovery. Discard pvc pipes as bulk garbage.","bulk (mostly metal or rigid plastic),bulk metal,bulk metals,large metal items,bulk plastic,bulk plastics,large plastic items,pvc pipe,pvc pipes,bulk rigid plastic,bulk"];
dispose_data[24] = ["bulk (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/specially-handled-items.shtml","learn more","Place large non-metal or plastic items out for collection the night before your garbage collection day. Sanitation will collect up to six items from one address. Other restrictions apply for yard waste, construction debris, and mattresses.","bulk (not mostly metal or rigid plastic),bulk,wood,concrete"];
dispose_data[25] = ["button battery","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Recycle at a jewelry store, watch repair shop, or camera store. Otherwise, discard as garbage or take to a household special waste drop-off site or upcoming DSNY SAFE disposal event (individually bag batteries or tape terminals before dropping off).","button battery,button batteries,watch battery,watch batteries,hearing aid battery,hearing aid batteries"];
dispose_data[26] = ["cables (loose)","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Check with retailers for take-back options. Otherwise, discard as garbage on regular collection day(s).","cables (loose),electronic cables,christmas tree lights,christmas tree,christmas trees,xmas tree,xmas trees,tree lights,holiday lights,extension cord,extension cords,power cord,power cords,a/v cords,usb cords,hdmi cables,cords,xmas,x-mas,christmas"];
dispose_data[27] = ["cameras","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Check with camera retailers for take-back options. Otherwise, discard as garbage on regular collection day(s).","cameras,camera,leica,camera lens,nikon,kodak,digital camera,digital cameras"];
dispose_data[28] = ["caps and lids","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle caps and lids with metal, glass, plastic, & cartons","caps and lids,metal cap,metal caps,metal lid,metal lids,plastic cap,plastic lid,caps and lids (plastic),caps and lids (metal),cap,caps,lid,lids,bottle cap,bottle caps"];
dispose_data[29] = ["carbonated beverage container","/assets/dsny/zerowaste/residents/deposit-bottles.shtml","learn more","Empty & rinse. Recycle with other metal, glass, plastic & cartons, or return to store for refund if there is a deposit on the container.","carbonated beverage container,soda water,seltzer,soda pop,soda,beer,deposit bottle/can,deposit container,deposit containers,deposit bottle,deposit can,deposit bottles,deposit cans"];
dispose_data[30] = ["cardboard","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle cardboard with your mixed paper. Flatten and bundle large pieces, or break into small pieces and place in recycling bin or bag.","box,boxes,cardboard,cardboard tube,cardboard tubes,paper towel tube,toilet paper tube,cardboard box,cardboard boxes,cereal box,cereal boxes,corrugated,shoe box,shoe boxes,laundry detergent box,pasta box,egg carton,egg carton (cardboard),eggs,CD/DVD cases (cardboard),CD case,CD case (cardboard),DVD case (cardboard)"];
dispose_data[31] = ["cardboard cannisters (metal tops/bottoms)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","These items are problematic to recycle; do not place in recycling bin. Discard as garbage on your regular collection day(s).","cardboard cannisters (metal tops/bottoms),comet,ajax,pringles"];
dispose_data[32] = ["carpet/rug","/assets/dsny/zerowaste/residents/home-improvement-waste.shtml","learn more","See if installer will take back old carpet or rug, or donate or sell if in good condition. Otherwise discard as bulk garbage on regular collection day(s) (remove all nails or staples and securely tie in bales no more than 2 feet high and 4 feet long).","carpet/rug,carpet,carpets,rug,rugs,floor covering"];
dispose_data[33] = ["cassettes/VHS tapes","/assets/dsny/zerowaste/residents/books-and-media.shtml","learn more","These items are problematic to recycle, do not place in recycling bin. Discard as garbage on your regular collection day(s).","cassettes/VHS tapes,cassette tapes,VHS tapes,video tapes,8 track tape,8 track tapes"];
dispose_data[34] = ["catalog","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle catalogs with mixed paper and cardboard. Take steps to remove your name from junk mail lists.","catalog,junk mail,publication"];
dispose_data[35] = ["CDs/DVDs/disks","/assets/dsny/zerowaste/residents/books-and-media.shtml","learn more","Donate or sell if in working condition; or recycle with metal, glass, plastic, & cartons.","CDs/DVDs/disks,Compact Disc,cd,disk,disks,dvd,cd-rom,computer,disk,CD,CDs,cd-rom,dvd,dvds,diskette,floppy,vinyl record,vinyl records,album,albums"];
dispose_data[36] = ["cell phone","/assets/dsny/zerowaste/residents/cell-phones.shtml","learn more","Recycle unwanted cell phones and accessories by dropping them off at retail locations sponsoring a take-back program. Can also be taken to upcoming DSNY SAFE disposal events. Cell phones should not be placed in the garbage unless the battery is removed.","cell phone,cell phones,cell,phone,cellular,mobile phone,mobile phones,iphone,iphones,smart phone,smart phones,android,smartphone,smartphones,blackberry,galaxy"];
dispose_data[37] = ["children's items","/assets/dsny/zerowaste/residents/childrens-items.shtml","learn more","Donate or sell if in good condition (certain restrictions apply). Otherwise discard as garbage or recycle when appropriate.","children's items,children's item,kid's items,baby items,child"];
dispose_data[38] = ["Christmas tree (fake - mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/christmas-trees.shtml","learn more","Donate or sell if in good condition. Remove ornaments and set out next to recycling container on your recycling day.","Christmas tree (fake - mostly metal or rigid plastic),plastic tree,plastic trees,fake tree,fake christmas tree,plastic christmas tree,plastic christmas trees,metal christmas tree"];
dispose_data[39] = ["Christmas tree (fake - not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/christmas-trees.shtml","learn more","Donate or sell if in good condition. Discard as garbage on regular collection day(s).","Christmas tree (fake - not mostly metal or rigid plastic),fake tree,fake trees,fake christmas tree,fake christmas trees"];
dispose_data[40] = ["Christmas tree (natural)","/assets/dsny/zerowaste/residents/christmas-trees.shtml","learn more","Remove all ornaments, lights, tinsel, and stands and take to MulchFest for free chipping or set out on regular collection day(s) in early January for DSNY composting collection. Trees set out at other times will be collected as bulk garbage.","Christmas tree (natural),christmas tree,x-mas,xmas tree,Xmas,Christmas,holiday tree,holiday trees"];
dispose_data[41] = ["cleaning products (labeled DANGER-corrosive)","/assets/dsny/zerowaste/residents/cleaning-products.shtml","learn more","Do not pour down the drain. Use up cleaning products instead of discarding. Cleaning products can be taken to upcoming DSNY SAFE disposal events. Otherwise, dry out any remaining cleaning products with kitty litter, newspaper, other absorbent material before discarding as garbage. Before discarding, double bag these containers (empty or dried out) and mark the bag DANGER - not for recycling.\"","cleaning products (labeled DANGER-corrosive),household cleaners,cleaners,bleach,ammonia,oven cleaners,drain cleaners,cleaners,pool cleaner"];
dispose_data[42] = ["cleaning products (NOT labeled DANGER-corrosive)","/assets/dsny/zerowaste/residents/cleaning-products.shtml","learn more","Use up cleaning products instead of discarding. Cleaning products can be taken to upcoming DSNY SAFE disposal events. Otherwise, dry out any remaining cleaning products with kitty litter, newspaper, other absorbent material before discarding as garbage. Empty containers can be recycled with metal, glass, plastic & cartons.","cleaning products (NOT labeled DANGER-corrosive),oven cleaners,drain cleaners,cleaners,household cleaners,cleaners,bleach,ammonia,pool cleaner"];
dispose_data[43] = ["clips (metal or plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic & cartons.","clips (metal or plastic),butterfly clips,metal paper clips,metal hair clips,binder clips,paper clips,chip clip,chip clips"];
dispose_data[44] = ["clothing and accessories","/assets/dsny/zerowaste/residents/textiles.shtml","learn more","Donate or sell if in good condition. Sign your building or business up for a re-fashioNYC clothing donation bin. Otherwise, discard as garbage on regular collection day(s).","clothing and accessories,clothing,shirt (clothing),pants (clothing),socks (clothing),t-shirt (clothing),clothes,coat,coats,jacket,jackets,shoes,sneakers,pants,costume,costumes,halloween costume,halloween costumes,sunglasses,belts,handbags,linens,towels,curtains,clean rags"];
dispose_data[45] = ["collectibles","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Otherwise recycle predominately metal or rigid plastic items or discard as garbage on regular collection day(s).","collectibles,antiques,jewelry,art,dolls,sculptures"];
dispose_data[46] = ["commercial waste","/assets/dsny/zerowaste/businesses/who-picks-up-recycling-and-garbage-for-businesses.shtml","learn more","Other than certain non-profits, institutions, and professional establishments doing business in residential buildings, DSNY does not provide service to private companies. Commercial buildings that do not qualify for DSNY service must follow commercial disposal guidelines.","commercial,commercial waste,hospital waste,business waste,industrial waste"];
dispose_data[47] = ["compact fluorescent light bulb (CFL)","/assets/dsny/zerowaste/residents/lighting.shtml","learn more","Contains minimal amount of mercury. Take back to retailer that accepts CFLs, or to household special waste drop-off site or upcoming DSNY SAFE disposal event. Can legally discard in garbage, but double bag for safety.","compact fluorescent light bulb (CFL),compact fluorescent light bulbs (CFL),compact fluorescent light,light (compact fluorescent),CFL,CFLs,compact,fluorescent,bulb,bulbs,lamp,fluorescent light (compact),spiral bulb,spiral bulbs"];
dispose_data[48] = ["computers and peripherals","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Otherwise recycle through a legally-mandated free take-back program for computers, monitors, keyboards, mice, scanners, printers, and small servers. Can be taken to upcoming DSNY SAFE disposal events. It is illegal to place electronic waste in the garbage.","computers and peripherals,electronics,electronic,computer,computers,computer system,PC,Mac,desktop,laptop,laptops,monitor,monitors,CRT,tower,CPU,CPUs,hard drive,hard drives,keyboard,keyboards,personal computer,personal computers,computer equipment,computer monitor,computer monitors,mouse,mice,server,computer peripherals,printer,printers,screen,CRT,cathode ray tube,scanner,scanners,flat-panel monitor,flat-panel monitors"];
dispose_data[49] = ["construction material (do-it-yourself)","/assets/dsny/zerowaste/residents/home-improvement-waste.shtml","learn more","Donate or sell if in good condition. Hire a private removal company for large projects. For smaller projects (generating six items or less), recycle metal and rigid plastic items (except pvc pipes) next to recycling containers on your recycling day; discard other items as garbage on regular collection day(s). Before setting out, remove or flatten sharp objects (nail, staples, etc.) and securely bag (no more than 60 lbs) or tie in bales (no more than 2 feet high and 4 feet long).","construction material (do-it-yourself),construction,building materials,construction materials,debris,demolition waste,C and D,asphalt,brick,bricks,concrete,gypsum,drywall,lumber,ceiling tiles"];
dispose_data[50] = ["construction material (from hired contractor)","/assets/dsny/zerowaste/residents/home-improvement-waste.shtml","learn more","Cannot be discarded as residential garbage. Contractor is responsible for the removal of this material. Request that contractor donate or sell if in good condition.","construction material (from hired contractor),construction,commercial,building materials,construction materials,debris,contractor,demolition waste,C and D,asphalt,brick,concrete,gypsum,drywall,plumber,electrician,carpenter,ceiling tiles"];
dispose_data[51] = ["cooking oil and grease","/assets/dsny/zerowaste/residents/specially-handled-items.shtml","learn more","Cooking oil and grease can be placed in a container, like a frozen juice container, a beverage carton, or a take-out container. Label the container \"Cooking Oil - Not for Recycling\" and discard with regular garbage. Alternately, put cooled cooking oil/grease in a plastic bag and freeze before discarding.","cooking oil and grease,cooking oil,frying oil,grease,waste oil,oil,olive oil,canola oil,vegetable oil,lard,deep fryer,deep fried"];
dispose_data[52] = ["cosmetics","/assets/dsny/zerowaste/residents/cosmetics.shtml","learn more","Some cosmetics can be mailed back to manufacturers for recycling. Otherwise discard cosmetic product in the garbage and recycle empty metal, glass or rigid plastic containers.","cosmetics"];
dispose_data[53] = ["degradable plastics","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic or cartons","degradable plastics,bioplastics,biodegradeable plastic,compostable plastic,bio-based plastic,plastic compostable,plastic biodegradable,plastic bio-based"];
dispose_data[54] = ["digital music player (portable)","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Otherwise recycle through a legally-mandated free take-back program. Can be taken to upcoming DSNY SAFE disposal events. It is illegal to place electronic waste in the garbage.","digital music player (portable),electronics,electronic,digital music player,digital music players,mp3 player,ipod,ipods"];
dispose_data[55] = ["disposable coffee pods","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons. Certain brands have take-back options, see manufacturers' website.","disposable coffee pod,disposable coffee pods,K-Cups,Nespresso,K Cup,K-Cup,K Cups"];
dispose_data[56] = ["eyeglasses","/assets/dsny/zerowaste/residents/eyeglasses.shtml","learn more","Donate or sell if in working condition. Otherwise, discard as garbage on regular pickup day(s).","eyeglasses,sunglasses"];
dispose_data[57] = ["fax machine (not connected to a computer)","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Check with retailers for take-back options. It is illegal to place electronic waste in the garbage.","fax machine (not connected to a computer),fax machine,fax machines,facsimile,fax"];
dispose_data[58] = ["fire extinguisher (CO2 or dry chemical)","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Contact a local FDNY-certified fire extinguisher retailer to refill. Otherwise, relieve the pressure, remove the head, and place in your recycling. Follow the National Fire Protection Association's PASS technique to ensure that you have appropriately emptied your fire extinguisher. Do not recycle unless the head is removed because fire extinguishers are pressurized and may explode when compressed in a truck. If you are unsure about the type of fire extinguisher, check the label.","fire extinguisher (CO2),CO2 extinguisher,carbon dioxide extinguisher,carbon dioxide fire extinguisher,CO2 fire extinguisher,fire extinguisher"];
dispose_data[59] = ["fire extinguisher (non CO2 or dry chemical)","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Old fire extinguishers and fire extinguishers that are not dry chemical or carbon dioxide may contain carbon tetrachloride, a known carcinogen. Do not place at the curb. Contact a local FDNY-certified fire extinguisher retailer to request that they dispose of your extinguisher. Can be taken to upcoming DSNY SAFE Disposal Events. If you are unsure about the type of fire extinguisher, check the label.","fire extinguisher (non CO2 or dry chemical),old fire extinguisher,carbon tetrachloride,fire extinguisher"];
dispose_data[60] = ["flammable liquids","/assets/dsny/zerowaste/residents/corrosive-and-flammable.shtml","learn more","Highly flammable liquids (such as gasoline) should never be disposed of at the curb or down the drain. Use the material up instead of disposing. Flammable liquids can be taken to upcoming DSNY SAFE disposal events. Otherwise, contact an appropriate private hazardous/chemical waste company.","flammable liquids,harmful household products,hazardous products,household hazardous waste,SAFE disposal,gas,gasoline,kerosene,fuel,fuels,flammable product,flammable products,lighter fluid,flare,flares"];
dispose_data[61] = ["fluorescent light tube","/assets/dsny/zerowaste/residents/lighting.shtml","learn more","Contains some mercury. Take to household special waste drop-off site or upcoming DSNY SAFE disposal event. Can legally discard in garbage, but double bag for safety.","fluorescent light tube,fluorescent light tubes,fluorescent,bulb,lamp,lamps,green tip lamp,u-shaped fluorescent lamp,u-shaped fluorescent lamps,circular fluorescent lamp"];
dispose_data[62] = ["food (non perishable)","/assets/dsny/zerowaste/residents/food-waste.shtml","learn more","Donate canned and packaged food. Otherwise drop it off for neighborhood composting. Alternatively, discard contents as regular garbage (food can be collected separately in organics collection pilot areas). Recycle the empty and rinsed food containers if metal, glass, plastic or cartons. (Discard foam containers.)","food (non perishable),food,edible food,canned goods,packaged foods,non perishable food,boxed food"];
dispose_data[63] = ["food (perishable fruit and vegetable scraps bread and grains)","/assets/dsny/zerowaste/residents/food-waste.shtml","learn more","Compost it at home or drop it off for neighborhood composting. Alternatively, discard as garbage on regular collection days (food can be collected separately in organics collection pilot areas). Recycle the empty and rinsed food containers if metal, glass, plastic or cartons. (Discard foam containers.)","food (perishable fruit and vegetable scraps bread and grains),food (perishable),food,edible food,fruit,vegetable,produce,perishable food,frozen food,corncob,corncobs,bread,grains,flour,spices,nutshells,egg shells,coffee grounds,coffee filters,tea,tea bags"];
dispose_data[64] = ["food (perishable meat dairy prepared foods)","/assets/dsny/zerowaste/residents/food-waste.shtml","learn more","Discard as garbage on regular collection days (food can be collected separately in organics collection pilot areas). Recycle the empty and rinsed food containers if metal, glass, plastic or cartons. (Discard foam containers.)","food (perishable meat dairy prepared foods),food (perishable),food,edible food,meat,fish,cheese,dairy,eggs,perishable food,frozen food"];
dispose_data[65] = ["food or beverage carton","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons.","food or beverage carton,food or beverage cartons,soup carton,soup cartons,asceptic packaging,aseptic packaging,tetra pak,tetra paks,milk carton,milk cartons,milk,carton,cartons,soy milk carton,soy milk cartons,juice and drink box/carton,juice carton,juice cartons,juice box,juice boxes,drink box,drink boxes"];
dispose_data[66] = ["furniture (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/furniture.shtml","learn more","Donate or sell if in good condition. Otherwise set out bulk metal and bulk plastic next to your recycling container on your recycling collection day.","furniture (moslty metal or rigid plastic),metal chair,metal chairs,folding chair,folding chairs,office chair,office chairs,metal desk,metal desks,metal furniture,patio furniture,office furniture,cabinet,cabinets,plastic,plastic furniture,plastic chair,plastic chairs,plastic table,plastic tables,table,tables,metal table,desk,chair,chairs,lawn,patio"];
dispose_data[67] = ["furniture (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/furniture.shtml","learn more","Donate or sell if in good condition. Otherwise discard as garbage on regular collection day(s).","furniture (not mostly metal or rigid plastic),office furniture,wood,chair,chairs,office chair,office chairs,cubicle,desk,desks,lawn,patio,cushion,cushions,umbrella,stand,table"];
dispose_data[68] = ["garden hose","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","These items are problematic to recycle, do not place in recycling bin. Discard as garbage on your regular collection day(s).","garden hose,hose"];
dispose_data[69] = ["gardening supplies (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Recycle with metal, glass, plastic or cartons","gardening supplies (mostly metal or rigid plastic),rake,rakes,shovel,shovels,stake,stakes,chicken wire"];
dispose_data[70] = ["gardening supplies (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate if in working order. Otherwise, discard as garbage on your regular collection day(s).","gardening supplies (not mostly metal or rigid plastic),rake,shovel,tarp,tarps,stake"];
dispose_data[71] = ["glass bottle/jar","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse and recycle with metal, glass, plastic & cartons (if broken, double-bag to prevent injury).","glass bottle/jar,glass bottles,glass jars,jar,jars,bottle,bottles,broken glass bottle,broken glass bottles,broken glass jar,broken glass jars"];
dispose_data[72] = ["glass window (metal frame)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Otherwise set out with other bulk metal items on your recycling collection day (tape glass before setting out for recycling collection).","glass window (metal frame),glass,glass window,glass windows,metal frame,metal frames,window,windows"];
dispose_data[73] = ["glass window (non-metal frame)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Otherwise discard with other bulk garbage items on regular collection day(s); tape glass before setting out for collection.","glass window (non-metal frame),glass,glass window,window"];
dispose_data[74] = ["glassware","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Otherwise, discard as garbage (if broken, double-bag to prevent injury). Bottles & jars are the only glass items that can be recycled with DSNY.","glassware,glass cup,glass cups,glass plate,glass plates,glass bowl,glass bowls,glass dish,glass dishes,glass mug,glass mugs,glass vase,broken glass,candle holders,candlestick holder,glass candle,glass candles,glass candlestick,glass candlesticks"];
dispose_data[75] = ["gps devices","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Check with retailers for take-back options. Otherwise, discard as garbage on your regular collection day(s).","gps devices"];
dispose_data[76] = ["grass clippings","/assets/dsny/zerowaste/residents/food-waste.shtml","learn more","Leave grass clippings on the lawn. Otherwise discard as regular garbage (if self-mowed), or separate it for DSNY organics collection if you are in a pilot organics neighborhood. Private landscapers can't leave clippings at the curb; they must be taken instead to a compost facility.","grass clippings,lawn,turf,lawn clippings,grass,mowed grass,yard waste"];
dispose_data[77] = ["hanger (metal or rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Bring back to drycleaner, reuse at home, or recycle with metal, glass, plastic, & cartons.","hanger (metal or rigid plastic),wire hanger,wire hangers,metal hanger,metal hangers,hanger,hangers,plastic hanger,plastic hangers"];
dispose_data[78] = ["hanger (non-metal or rigid plastic)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Bring back to drycleaner, reuse at home, or discard as garbage on regular collection day(s).","hanger (non-metal or rigid plastic),hanger,wood hanger,wood hangers"];
dispose_data[79] = ["hanging folder","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Separate metal hangers from paper. Remaining paper can be recycled with mixed paper and cardboard and the metal hangers can be recycled with metal, glass, plastic & cartons.","hanging folder,hanging folders,file folder,file folders"];
dispose_data[80] = ["headphones","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Check with retailers or manufacturers for take-back options. Otherwise, discard as garbage on your regular collection day(s).","headphones,earbuds"];
dispose_data[81] = ["helium balloon tank","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Portable helium tanks can be recycled with bulk metal once they are emptied, the pressure has been relieved, and the head has been removed. Do not recycle unless the head is removed because the tanks are pressurized and may explode when compressed in a truck.","helium,helium tank,helium balloon tank"];
dispose_data[82] = ["highly corrosive liquids","/assets/dsny/zerowaste/residents/corrosive-and-flammable.shtml","learn more","Highly corrosive liquids (such as hydrofluoric, sulfuric, or muriatic acids) should never be disposed of at the curb or down the drain. Use the material up instead of disposing. Highly corrosive liquids can be taken to upcoming DSNY SAFE disposal events. Otherwise, contact an appropriate private hazardous/chemical waste company. Empty containers cannot be recycled and must be discarded as garbage. Before putting in the garbage double bag these containers and mark the bag \"DANGER - not for recycling.\"","highly corrosive liquids,harmful household products,hazardous products,household hazardous waste,SAFE disposal,corrosive product,acid,muriatic acid,hydrofuoric acid,hydrochloric acid,sulfuric acid,pool chemicals"];
dispose_data[83] = ["household chemicals","/assets/dsny/zerowaste/residents/cleaning-products.shtml","learn more","Use up instead of discarding. Household chemicals can  be taken to upcoming DSNY SAFE disposal events. Other than highly corrosive or flammable liquids, small quantities of household chemicals can be discarded at the curb.  Dry out any remaining cleaning products with kitty litter, newspaper, other absorbent material before discarding as garbage. Empty containers can be recycled as applicable unless labeled \"DANGER - Corrosive\"; these containers may be put in the garbage, provided they are double-bagged and the bag is marked \"DANGER - not for recycling.\"","household chemicals,harmful household products,hazardous products,household hazardous waste,SAFE disposal,nail polish,nail polish remover,moth balls,turpentine,superglue,adhesive,glue,photo chemicals,rubbing alcohol,silver polish,metal polish,rubber cement"];
dispose_data[84] = ["household sharps","/assets/dsny/zerowaste/residents/household-medical-waste.shtml","learn more","Carefully place in leak-proof and puncture-resistant container labeled \"Home Sharps - not for recycling\" and discard as regular garbage. Otherwise bring to any hospital or nursing home in NY State (some pharmacies may accept them as well). Household sharps can also be taken to upcoming DSNY SAFE disposal events.","household sharps,medical equipment,syringes,lancets,medical material,medical materials,hypodermic needle,sharp,sharps,shot,needle,needles,IV needles,intravenous needles"];
dispose_data[85] = ["houseplants and flowers","/assets/dsny/zerowaste/residents/yard-waste.shtml","learn more","Discard as garbage on your regular collection day(s). Houseplants and flowers can be composted at home, or brought to an organics drop-off site. Recycle metal and rigid plastic flower pots with metal, glass, plastic & cartons. (Discard foam containers.)","houseplants and flowers,bouquet,potting soil,potted plant,plants"];
dispose_data[86] = ["housewares (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Otherwise, recycle any metal with metal, glass, plastic & cartons.","housewares (metal or rigid plastic),housewares,utensils,pots,pans,curtain rods,iron,metal lock,metal locks,pad lock,pad locks,metal bucket,metal buckets,plastic,bucket,chain,chains,tools,screwdriver,screwdrivers,hammer,hammers,nails,bolts,nuts,screws,wrench,wrenches,shelving,spoon,spoons,fork,forks,spatula,spatulas,collander,metal bowl,metal bowls,metal mixing bowl,metal mixing bowls,plastic mixing bowl,plastic mixing bowls,metal,measuring cup,measuring cups,cooking,metal cookie sheet,metal cookie sheets,metal rack,metal racks,candle holders,candlestick holder,plastic collander,plastic utensils,plastic cooking spoon,plastic cooking spoons,bucket,brush,comb,combs,hamper,dish rack,dish racks,drying rack,window blinds,vinyl blinds,venetian blinds,aluminum blinds,metal blinds,blind,blinds"];
dispose_data[87] = ["housewares (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","If applicable, donate or sell if in good condition. Otherwise discard with regular garbage. For safety, double bag broken glass and tape large glass items before setting out for collection.","housewares (non-metal or rigid plastic),ceramic,ceramics,bowl,bowls,cup,cups,vase,mug,mugs,mixer,pyrex,tub,basket,baskets,hamper,dish rack,drying rack,cooler,coolers,wood hanger,fish tank,aquarium,mirror,mirrors,flower pot,planter,crate,tools,brush,brushes,comb,spatula,candle holder,candlestick holder,candle,drinking glass,saucer,shower curtain,window blinds,vinyl blinds,venetian blinds,aluminum blinds,metal blinds,blind,blinds"];
dispose_data[88] = ["knife/sharp metal object","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in good condition. Knives or similar sharp metal objects should be securely wrapped in cardboard and labeled \"CAUTION: SHARP\" before being recycled with metal, glass, plastic & cartons. Dangerous items such as razor blades and disposable razors should be discarded as garbage.","knife/sharp metal object,knives,sharp metal,metal knife,metal knives,saw,saws,razors,disposable razor,disposable razors,plastic razor,plastic razors"];
dispose_data[89] = ["large appliance (mostly metal or rigid plastic no CFCs)","/assets/dsny/zerowaste/residents/appliances.shtml","learn more","Donate or sell if in good condition. Otherwise setout with other bulk metal or rigid plastic items on your recycling collection day. For safety reasons, remove doors before setting them out.","large appliance (mostly metal or rigid plastic no CFCs),clothes dryer,gas clothes dryer,electric clothes dryer,dryer,metal appliance.dishwasher,washing machine,washing machines,stove,water heater,water heaters,dishwasher,dishwashers,appliances,plastic appliances,copy machine"];
dispose_data[90] = ["leaf and yard waste (do-it-yourself)","/assets/dsny/zerowaste/residents/yard-waste.shtml","learn more","Leaf and yard waste generated by homeowners can be set out for curbside collection if your home is in a neighborhood that receives DSNY organics collection.","leaf and yard waste (do-it-yourself),yard waste,leaf,leaves,grass,flowers,twigs,bushes"];
dispose_data[91] = ["leaf and yard waste (from hired landscaper)","/assets/dsny/zerowaste/businesses/commerical-landscaper-waste.shtml","learn more","Yard waste generated by landscapers can't be set out for curbside collection or dispersed in or around the curb or street. Landscapers must dispose of yard waste they generate at a permitted composting facility.","leaf and yard waste (from hired landscaper),yard waste,leaf,leaves,grass,flowers,twigs,bushes,landscaper,professional landscaper"];
dispose_data[92] = ["license plates","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Most plates should be surrendered to NYS DMV. Plates that are replaced by custom plates, personalized plates, or Empire Gold plates should be defaced and recycled with metal, glass, plastic & cartons.","license plate,license plates,empire gold plates,vehicle plates,motorcycle plates"];
dispose_data[93] = ["light bulb (incandescent or LED)","/assets/dsny/zerowaste/residents/lighting.shtml","learn more","Double bag for safety and discard as garbage on regular collection day(s).","light bulb (incandescent),bulb,lightbulb,lightbulbs,LED,LEDs,LED light bulb,LED light bulbs,LED light,LED lights"];
dispose_data[94] = ["lighters","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items are problematic to recycle, do not place in recycling bin. Discard as garbage on regular collection day(s).","lighters"];
dispose_data[95] = ["lighting fixtures/lamps (metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in working condition. Otherwise, recycle with metal, glass, plastic & cartons; or with other bulk metal or rigid plastic items on your recycling collection day.","lighting fixtures/lamps (metal or rigid plastic),lamp,light fixture,light fixtures,plastic lamp,plastic lamps,plastic light fixture,plastic light fixtures,metal lamp,metal lamps,metal light fixture,metal light fixtures,floor lamp,floor lamps,metal lighting,chandelier,track lighting"];
dispose_data[96] = ["luggage/suit case","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Donate or sell if in good condition. Otherwise set out as bulk garbage on regular collection day(s).","luggage/suitcase,luggage,suitcase,suitcases,suit case"];
dispose_data[97] = ["mail","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Remove your name from junk mail lists; shred for security. Recycle paper mail with mixed paper and cardboard (window envelopes are OK).","mail,junkmail,envelopes,window envelopes"];
dispose_data[98] = ["mattress","/assets/dsny/zerowaste/residents/specially-handled-items.shtml","learn more","Must fully enclose within a sealed plastic bag (to prevent spread of bed bugs) and discard as bulk garbage on regular collection day(s). Bedding cannot be donated.","mattress,mattresses,broken,bed,beds,futon"];
dispose_data[99] = ["medical equipment  (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/medical-equipment.shtml","learn more","Donate or sell if in good condition. Otherwise set out next to your recycling container on your recycling collection day.","medical equipment,crutches,wheelchairs,prosthetic limbs,boot (medical),braces,brace,walker,crutch"];
dispose_data[100] = ["medical equipment (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/medical-equipment.shtml","learn more","Donate or sell if in good condition. Otherwise, discard as garbage on regular collection day(s).","medical equipment,crutches,wheelchairs,prosthetic limbs,boot (medical),braces,brace,walker,crutch"];
dispose_data[101] = ["medical waste (household- other than sharps or medications)","/assets/dsny/zerowaste/residents/household-medical-waste.shtml","learn more","Use securely tied bags and discard as garbage on regular collection day(s).","medical waste,soiled bandages,disposable sheets,medical gloves,tubing (medical),intravenous bags and tubes,IV bags and tubes"];
dispose_data[102] = ["mercury (liquid)","/assets/dsny/zerowaste/residents/mercury-containing-devices.shtml","learn more","Do not discard; Liquid mercury can be taken to upcoming DSNY SAFE disposal events. Otherwise, contact an appropriate private hazardous/chemical waste company.","mercury (liquid),liquid mercury,dental amalgum"];
dispose_data[103] = ["mercury thermometers and other mercury containing devices","/assets/dsny/zerowaste/residents/mercury-containing-devices.shtml","learn more","Illegal to discard in garbage; take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","mercury thermometers and other mercury containing devices,thermometers,thermometer,mercury devices,mercury containing devices,sphygmometers,blood pressure cuffs"];
dispose_data[104] = ["metal can","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty and rinse and recycle with metal, glass, plastic, & cartons.","metal can,metal cans,coffee can,soup can,soup cans,tuna can,canned,can,cans"];
dispose_data[105] = ["microwave (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Donate or sell if in working condition. Otherwise set out next to your recycling container on your recycling collection day.","microwave (mostly metal or rigid plastic),microwave,microwaves,metal microwave,plastic microwave"];
dispose_data[106] = ["microwave (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Donate or sell if in working condition. Check with retailers for take-back options. Otherwise, discard as garbage on regular collection day(s).","microwave (not mostly metal or rigid plastic),microwave"];
dispose_data[107] = ["mixed paper","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with mixed paper and cardboard. You don't need to remove staples. Tear or shred for privacy as needed. Soiled paper should be discarded as garbage.","mixed paper,paper bag,paper bags,paper cups (unsoiled),file folder,pads,colored paper,white paper,craft paper,lined paper,notebook paper,business cards,construction paper,tickets,stubs,flyers,brochures,paper plates (unsoiled),manila folder,manila folders,fax paper,paper shopping bag,shopping bags,statements,report,bill,document,gift wrap,paper,wrapping,wrapping paper,tissue paper (from gifts),copy paper,notebook,office paper,folder,paper plate,CD/DVD cases (cardboard),case,cases,DVD case,DVD cases,CD case,CD case (cardboard),DVD case (cardboard)"];
dispose_data[108] = ["motor oil","/assets/dsny/zerowaste/residents/motor-oil.shtml","learn more","Service stations that change oil must accept up to five gallons of used motor oil (including transmission fluid) per day, per person, at no charge. Motor oil is also accepted at household special waste drop-off sites and SAFE Disposal events. ","motor oil,auto fluids,transmission fluid,brake fluid,oil,waste oil"];
dispose_data[109] = ["motor oil filter","/assets/dsny/zerowaste/residents/motor-oil.shtml","learn more","Check with service stations to see if they'll accept them, or take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","motor oil filter,filter (motor oil),oil filter,oil filters"];
dispose_data[110] = ["musical instrument (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/musical-instruments.shtml","learn more","Donate or sell if in working condition. Otherwise recycle with metal, glass, plastic, & cartons; or set out as bulk metal or bulk plastic next to recycling container on your recycling day.","musical instrument (mostly metal or rigid plastic),musical instruments,brass instrument,brass instruments,woodwind,steel drum,steel drums,flute,clarinet,saxophone,trumpet,horn,tuba,bugel,cymbals"];
dispose_data[111] = ["musical instrument (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/musical-instruments.shtml","learn more","Donate or sell If in working condition. Otherwise discard as regular or bulk garbage on regular collection day(s).","musical instrument (not mostly metal or rigid plastic),guitar,guitars,wood instrument,string instrument,string instruments,cello,drum,drums,keyboard,recorder,piano,violin,harp"];
dispose_data[112] = ["newspapers magazines and catalogs","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Opt out of unwanted catalogs. Recycle with mixed paper and cardboard.","newspapers magazines and catalogs,newspaper,newspapers,magazine,magazines,catalog,catalogs"];
dispose_data[113] = ["office supplies (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if valuable and in good condition. Otherwise recycle with metal, glass, plastic & cartons.","office supplies (mostly metal or rigid plastic),rubber bands,scotch tape,tape dispenser,tape dispensers,paper weight,folder organizer"];
dispose_data[114] = ["office supplies (other than paper metal rigid plastic or electronics)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if valuable and in good condition. Otherwise discard as garbage on regular collection day(s).","office supplies (other than paper metal rigid plastic or electronics),rubber bands,scotch tape,tape dispenser,paper weight,folder organizer"];
dispose_data[115] = ["office supplies (paper & cardboard)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if valuable and in good condition. Otherwise recycle with mixed paper and cardboard.","office supplies (paper & cardboard),rubber bands,scotch tape,tape dispenser,paper weight,folder organizer,writing instruments,manila folder"];
dispose_data[116] = ["other gas tanks (acetylene or oxygen or other)","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Do not attempt to relieve the pressure or remove the head, and do not discard in the garbage or recycling. Contents may be hazardous and pressurized tanks may explode when compressed in a truck. Exchange your old pressurized gas tank when purchasing a new one, or bring to a scrap metal dealer.","gas,gas tanks,pressurized tanks,oxygen tank,acetylene,gas cylinder"];
dispose_data[117] = ["paint (latex) in metal or rigid plastic can or bucket","/assets/dsny/zerowaste/residents/paint.shtml","learn more","For non-dried out latex (water-based/acrylic) paint, look for reuse options, or take to household special waste drop-off site or upcoming DSNY SAFE disposal events. To discard as garbage, remove lid and let paint dry, or use kitty litter, newspaper, or other absorbent material to soak up paint. If can is empty, recycle with metal, glass, plastic & cartons.","paint (latex) in metal can,paint,latex paint,metal paint can,metal paint cans,acrylic,water based paint,paint (latex),paint (acrylic),paint(water-based),bucket,buckets,plastic can,plastic bucket,plastic buckets,metal bucket"];
dispose_data[118] = ["paint (latex) in non-metal or plastic can or bucket","/assets/dsny/zerowaste/residents/paint.shtml","learn more","For non-dried out latex (water-based/acrylic) paint, look for reuse options, or take to household special waste drop-off site or upcoming DSNY SAFE disposal events. To discard as garbage, remove lid and let paint dry, or use kitty litter, newspaper, or other absorbent material to soak up paint. If can is empty, recycle with metal, glass, plastic & cartons.","paint (latex) in non-metal or plastic can or bucket,paint,latex paint,paint tube,paint tubes,acrylic,water based paint,paint (latex),paint (acrylic),paint(water-based)"];
dispose_data[119] = ["paint (non-latex) in metal or rigid plastic can or bucket","/assets/dsny/zerowaste/residents/paint.shtml","learn more","For non-dried out oil-based (non-latex) paint, look for reuse options. Paint can be taken to upcoming DSNY SAFE disposal events. Otherwise, to discard as garbage; remove lid and use kitty litter, newspaper, or other absorbent material to soak up paint. If can is empty, recycle with metal, glass, plastic & cartons.","paint (non-latex) in metal can,paint,oil-based paint,metal paint can,oil paint,oil paints,outdoor paint,alkyd,bucket,plastic can,plastic cans,plastic bucket,metal bucket"];
dispose_data[120] = ["paint (non-latex) in non-metal or plastic can or bucket","/assets/dsny/zerowaste/residents/paint.shtml","learn more","For non-dried out oil-based (non-latex) paint, look for reuse options. Paint can be taken to upcoming DSNY SAFE disposal events. Otherwise, to discard as garbage, remove lid and use kitty litter, newspaper, or other absorbent material to soak up paint.","paint (non-latex) in non-metal can,paint,oil-based paint,plastic paint can,plastic paint cans,oil paint,outdoor paint,alkyd,paint tube,artist paint"];
dispose_data[121] = ["pens/markers","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items are problematic to recycle, do not place in recycling bin. Discard as garbage on regular collection day(s).","pens/markers,pens,sharpie,marker,markers,bic,pen,pencil,pencils,writing instruments"];
dispose_data[122] = ["personal hygiene items","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Discard as garbage on regular collection day(s).","personal hygiene items,diaper,diapers,cloth diaper,cloth diapers,disposable diaper,disposable diapers,tampon,tampons,pad,condom,condoms,toilet paper,bandage,bandages,bandaid,bandaids,disposable bandage,disposable bandages"];
dispose_data[123] = ["pesticides","/assets/dsny/zerowaste/residents/pesticides.shtml","learn more","Use up instead of discarding. Pesticides can be taken to upcoming DSNY SAFE disposal events. Otherwise, small quantities of pesticides can be discarded at the curb. Dry out any liquids with kitty litter, newspaper, other absorbent material before discarding as garbage. Empty containers can be recycled as applicable.","pesticides,harmful household products,hazardous products,household hazardous waste,SAFE disposal,herbicides,bug killers,bug spray,roach spray,ant spray,roach motel,roach motels,insecticide"];
dispose_data[124] = ["pizza box","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with mixed paper and cardboard. Be sure to remove food scraps.","pizza box,pizza boxes,pizza,pizza box (no food scraps),pizza box (with food scraps)"];
dispose_data[125] = ["plastic bag","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Reuse at home; bring to local stores for recycling; do not place in home recycling bin; discard as garbage on regular collection day(s).","plastic bag,plastic bags,plastic,plastics,bag,dry cleaning bags,delivery bags,newspaper bags,plastic film,grocery bag,grocery bags,shopping bag"];
dispose_data[126] = ["plastic envelopes","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Discard as garbage on regular collection day(s). Only rigid plastics can be recycled with DSNY. Take-back programs may be available.","tyvek,fedex pak,UPS pak,ups,fed ex,plastic envelopes,plastic shipping envelopes,mail"];
dispose_data[127] = ["plastic flexible packaging","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Discard as garbage on regular collection day(s). Only rigid plastics can be recycled with DSNY. Take-back programs may be available.","plastic flexible packaging,pouch,drink pouch,drink pouches,food pouch,food pouches,cleaner refill,laundry pouch,baby food pouch,baby food pouches,toothpaste tubes,flexible plastic packaging"];
dispose_data[128] = ["plastic food wraps and wrappers","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Discard as garbage on regular collection day(s). Only rigid plastics can be recycled with DSNY. Take-back programs may be available.","candy wrapper,chip bag,chip bags,bags,hot cereal bag,oatmeal wrapper,cereal bags"];
dispose_data[129] = ["plastic photographic film","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Discard as garbage on regular collection day(s). Only rigid plastics can be recycled with DSNY.","film,camera film,35 mm,xray,x-ray,MRI,mammogram,35 mm film,xray film,x-ray film,MRI film,mammogram film"];
dispose_data[130] = ["plastic rigid container (food and beverage)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons. Discard all foam items.","plastic rigid container (food and beverage),deli container,deli containers,hummus container,salad container,salad containers,takeout container,take-out container,take out container,takeout containers,take-out containers,take out containers,yogurt container,yogurt containers,food storage container,food storage containers,dairy containers,plastic lid,plastic lids,plastic cap,plastic caps,margarine tubs,plastic clamshells,egg carton,egg cartons,clam shells,clamshells,clam shells,tub,deli tub,yogurt tub,dairy tub,butter tub,food (yogurt),yoghurt,yogurt,brita filter,salad bowl,tub,plastic bottle/jug,energy drink,drink,juice,fruit juice,iced tea,soda bottle,soda bottles,jug,jugs,milk jug,milk jugs,plastic bottle,plastic bottles,plastic jug,plastic jugs,vitamin bottle,vitamin bottles,peanut butter jar,peanut butter tub,egg carton,egg carton (rigid plastic),eggs,tupperware,medicine bottle (empty),pill bottle (empty),vitamin bottle,rigid container,rigid plastic,water filter"];
dispose_data[131] = ["plastic rigid container (household chemicals DANGER-corrosive)","/assets/dsny/zerowaste/residents/cleaning-products.shtml","learn more","Do not pour down the drain. Use up cleaning products instead of discarding. Cleaning products can be taken to upcoming DSNY SAFE disposal events. Otherwise, dry out any remaining cleaning products with kitty litter, newspaper, or other absorbent material before discarding as garbage. If the container is labeled DANGER - corrosive, double bag these containers (empty or dried out) and mark the bag \"DANGER - not for recycling\" before putting in the garbage.","plastic rigid container (household chemicals DANGER-corrosive),#5 rigid plastic containers,cleaning products (labeled DANGER-corrosive),household cleaners,cleaners,bleach,ammonia,cleaning products (NOT labeled DANGER-corrosive),oven cleaners,drain cleaners,cleaning products,plastic bottle,plastic jug,plastic jar,plastic jars,dishwasher detergent,bathroom cleaner,toilet bowl cleaner,window cleaner,antifreeze"];
dispose_data[132] = ["plastic rigid container (non food or chemical)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons.","plastic rigid container (non food or chemical),shampoo,shampoo bottle,lotion,lotion bottle,hair gel,soap,shower gel,bath gel,liquid soap,soft soap,detergent,detergents,plastic bottle,plastic jug,plastic jar,antifreeze,coolant,CD/DVD cases (plastic),case,cassette tape cases,rigid container,rigid plastic,toiletries,DVD case (plastic),CD case (plastic),DVD case,CD case"];
dispose_data[133] = ["plastic rigid packaging","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons.","plastic rigid packaging,plastic packaging,tamper-proof packaging,mail order packaging,product packaging,display packaging,plastic clamshells,clamshells,clam shells,acetate box,blister pak,CD/DVD cases (rigid plastic),CD/DVD cases"];
dispose_data[134] = ["plastic rings","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Discard as garbage on your regular collection day(s). Cut rings before discarding to prevent injury to birds and aquatic animals. Rigid plastics are the only plastics that can be recycled with DSNY.","plastic rings,six-pack rings,six pack rings,soda rings,beer rings"];
dispose_data[135] = ["plastic shipping packaging","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Recycle through take-back program, or discard as garbage. Rigid plastics are the only plastics that can be recycled with DSNY.","plastic shipping packaging,packaging peanuts,styrofoam peanuts,air-filled plastic,air filled plastic,bubble wrap,foam peanuts,air pilllows"];
dispose_data[136] = ["plastic wrap/plastic food bags","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","Discard as garbage on your regular collection day(s). Rigid plastics are the only plastics that can be recycled with DSNY.","plastic wrap/plastic food bags,wrap,saran wrap,ziploc,zip lock,baggies,produce bags,food bags,paper towel wrapper,packaging wrap,shrink wrap"];
dispose_data[137] = ["plumbing (metal)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic & cartons, or set out next to recycling container on your recycling day.","plumbing (metal),metal pipes,metal faucet,metal sink,plumbing"];
dispose_data[138] = ["plumbing (non-metal)","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items are problematic to recycle; do not place in recycling bin. Discard as garbage on your regular collection day(s).","plumbing (non-metal),pipes,faucet,sink,pvc pipe,plastic pipe,plumbing"];
dispose_data[139] = ["print cartridges","/assets/dsny/zerowaste/residents/ink-and-toner-cartridges.shtml","learn more","Take back to some retailers or manufacturers; donate to charitable fundraisers; Otherwise Discard as garbage on your regular collection day(s).","print cartridges,ink,toner,printer cartridge,printer cartridges,inkjet"];
dispose_data[140] = ["propane tanks","/assets/dsny/zerowaste/residents/gas-tanks.shtml","learn more","Do not discard in the garbage or recycling. Propane is highly flammable. Exchange your empty propane tank for a full one at any local propane tank dealer. If you are not exchanging your tank, ask the dealer to dispose of it properly, or bring it to a scrap metal dealer. Can also be taken to upcoming DSNY SAFE Disposal Events.","propane,propane tank,gas tank,gas cylinder"];
dispose_data[141] = ["protective packaging (foam)","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items cannot be recycled, do not place in recycling bin. Discard as garbage on your regular collection day(s).","protective packaging (foam),computer box packaging,stereo box packaging,foam corners,styrofoam corners"];
dispose_data[142] = ["protective packaging (paper or cardboard)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with mixed paper and cardboard.","protective packaging (paper or cardboard),computer box packaging,stereo box packaging,cardboard box corners"];
dispose_data[143] = ["protective packaging (rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic & cartons. Discard foam items as garbage.","protective packaging (rigid plastic),computer box packaging,stereo box packaging,plastic corners"];
dispose_data[144] = ["shredded paper","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with mixed paper and cardboard.","shredded paper,paper"];
dispose_data[145] = ["single-use food service items (foam)","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items cannot be recycled, do not place in recycling bin. Discard as garbage on your regular collection day(s).","single-use food service items (foam),egg carton (foam),egg carton,eggs,styrofoam egg carton,styrofoam egg cartons,takeout container,take-out container,take out container,styrofoam,expanded polystyrene foam,clam shells,clamshells,cup,disposable cup,foam cup,foam cups,styrofoam cup,styrofoam cups,bowl,disposable bowl,disposable bowls,foam bowl,styrofoam bowl,disposable plate,plate,plates,foam plate,styrofoam plate,soup bowl,foam soup bowl,styrofoam soup bowl,styrofoam tray,foam tray,tray,lunch tray,disposable partyware,foam partyware,coffee cup,ice cream cup"];
dispose_data[146] = ["single-use food service items (not rigid plastic or paper)","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items cannot be recycled, do not place in recycling bin. Discard as garbage on your regular collection day(s).","single-use food service items (not rigid plastic or paper),disposable cutlery,disposable silverware,disposable partyware,cutlery,cup,disposable cup,disposable cups,utensils,silverware,plate,bowl,sugar packets,condiment packets,condiments,ketchup packets,salt packets"];
dispose_data[147] = ["single-use food service items (paper or cardboard)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","If unused or not soiled, recycle with mixed paper and cardboard. Empty drink cups can be recycled. Otherwise, garbage on your regular collection day(s).","single-use food service items (paper or cardboard),disposable partyware,cup,disposable cup,disposable cups,paper plate,soiled paper plate,soiled paper plates,paper cup,coffee cup"];
dispose_data[148] = ["single-use food service items (rigid plastic - not foam)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic & cartons. Discard foam items as garbage.","single-use food service items (rigid plastic - not foam),plastic cup,plastic cups,plastic straw,plastic straws,plastic plate,plastic plates,plastic fork,plastic forks,plastic knife,plastic knives,plastic spoon,plastic spoons,plastic cutlery,plastic utensils,disposable partyware,disposable cutlery,disposable silverware,plastic bowl,plastic bowls,cutlery,disposable cup,utensils,silverware,rigid plastic,rigid container,coffee cup,iced coffee cup"];
dispose_data[149] = ["small appliance (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in working condition. Otherwise, recycle with metal, glass, plastic & cartons.","small appliance (mostly metal or rigid plastic),toaster,blender,mixer,iron,toaster oven,toaster ovens,beer dispensers,baby food maker,bottle warmer,juicer,bread machine,electric can opener,coffee maker,coffee grinder,espresso maker,deep fryer,electric grill,electric grills,griddle,humidifier,tea kettle,tea kettles,food processor,food dehydrator,ice cream maker,meat slicer,meat grinder,popcorn maker,steamer,rice cooker,rice cookers,pressure cooker,slow cooker,slow cookers,crock pot,crock pots,roaster oven,roaster ovens,pizza oven,vacuum cleaner,vacuum,vacuum sealer,waffle maker,water dispenser,appliance,appliances,hair dryer,turntable,cassette player,record player,stereo,speakers"];
dispose_data[150] = ["small appliance (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in working condition. Otherwise, discard as bulk or regular garbage on your regular collection day(s).","small appliance (not mostly metal or rigid plasic),toaster,blender,mixer,iron,toaster oven,beer dispensers,baby food maker,bottle warmer,juicer,bread machine,electric can opener,coffee maker,coffee grinder,espresso maker,deep fryer,electric grill,griddle,tea kettle,food processor,food dehydrator,ice cream maker,meat slicer,meat grinder,popcorn maker,steamer,rice cooker,pressure cooker,slow cooker,crock pot,roaster oven,pizza oven,vacuum cleaner,vacuum,vacuum sealer,waffle maker,water dispenser,appliance,appliances,turntable,cassette player,record player,stereo,speakers"];
dispose_data[151] = ["small appliance (with rechargeable batteries)","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Donate or sell if in good condition. Otherwise, bring item to any store that sells this product so rechargeable battery can be properly discarded. NY State's Rechargeable Battery mandates that stores that sell rechargeable batteries (or products containing rechargeable batteries) must take back up to ten batteries of the same shape and size as they sell, free of charge.","electric toothbrush,digital camera,electric drill,electric razor,e-cigarettes,e-cigarette,appliance,appliances"];
dispose_data[152] = ["smoke detectors (optical) or carbon monoxide detectors","/assets/dsny/zerowaste/residents/smoke-detectors.shtml","learn more","Optical or photoelectric smoke detectors and carbon monoxide detectors do not contain any dangerous or radioactive material and require no special handling. Place these items in the regular garbage. If you are unsure about the type of smoke detector, check the label.","smoke detectors (optical),smoke detector,carbon monoxide detector,photoelectric smoke detector,optical smoke detector"];
dispose_data[153] = ["smoke or carbon monoxide detectors (ionization)","/assets/dsny/zerowaste/residents/smoke-detectors.shtml","learn more","Ionization smoke or carbon monoxide detectors contain tiny amounts of radioactive material (although there is no danger to their use). Return used smoke detectors to a manufacturer or take to an upcoming SAFE disposal event. Otherwise place in your garbage. If you are unsure about the type of smoke detector or carbon monoxide detector, check the label.","smoke detectors (ionization),smoke detector,ionization smoke detector"];
dispose_data[154] = ["sofa bed","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Must fully enclose mattress within a sealed plastic bag (to prevent spread of bed bugs). Discard sofa and enclosed mattress as bulk garbage on your regular collection day(s). (Bedding cannot be donated.)","sofa bed,sofa beds,pullout couch,pull out couch,pull-out couch,futon,couch,sofa"];
dispose_data[155] = ["soiled paper","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","These items are problematic to recycle; do not place in recycling bin. Discard as garbage on your regular collection day(s). Paper towels, napkins, plates, and tissues can be composted at home or brought to a food-scrap drop-off site.","non-recyclable paper,paper napkin,paper napkins,paper plate (soiled),soiled paper plate,paper towel,paper towels,tissues,toilet paper,ice cream containers,ice cream tubs,soiled paper,paper plate,paper plates"];
dispose_data[156] = ["sponges","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items are problematic to recycle; do not place in recycling bin. Discard as garbage on your regular collection day(s).","sponge,sponges"];
dispose_data[157] = ["sport equipment (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/sport-equipment.shtml","learn more","Donate or sell if in working condition. Otherwise recycle with metal, glass, plastic, & cartons.","sport equipment (mostly metal or rigid plastic),metal bat,plastic bat,bats,metal poles,metal raquet,metal raquets,bicycle,bicycles,bike,bikes,club,sports equipment,sporting equipment,treadmill,exercise equipment (mostly metal or rigid plastic)"];
dispose_data[158] = ["sport equipment (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/sport-equipment.shtml","learn more","Donate or sell if in working condition. Otherwise discard as bulk or regular garbage on your regular collection day(s).","sport equipment (not mostly metal or rigid plastic),bike,bikes,bicycle,bicycles,raquet,raquets,glove,gloves,mitt,mask,masks,helmet,helmets,goggles,ball,balls,net,nets,bat,skates,sticks,blades,skis,gear,club,roller skates,plastic roller skates,wooden bat,basketball,bowling ball,bowling balls,sports balls,baseball,sports equipment,sporting equipment,yoga mat,thermarest,camping mat,exercise equipment (not mostly metal or rigid plastic)"];
dispose_data[159] = ["tablets and e-readers","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Otherwise recycle through a legally-mandated free take-back program. Can be taken to upcoming DSNY SAFE disposal events.  It is illegal to place electronic waste in the garbage.","tablets and e-readers,electronics,electronic,tablet,e-reader,ereader,ipad,ipads,kindle,nook"];
dispose_data[160] = ["telephone (non-mobile)","/assets/dsny/zerowaste/residents/housewares.shtml","learn more","Donate or sell if in working condition. Check with retailers for take-back options. Otherwise, recycle with metal, glass, plastic, & cartons.","telephone (non-mobile),telephone,telephones,phone,phones,wall phone,cordless phone"];
dispose_data[161] = ["telephone book","/assets/dsny/zerowaste/residents/junk-mail.shtml","learn more","Request to opt out of phone books; recycle unwanted phone books with mixed paper and cardboard.","telephone book,telephone books,phone,book,directory,yellow pages,white pages"];
dispose_data[162] = ["thermostats (mercury)","/assets/dsny/zerowaste/residents/mercury-containing-devices.shtml","learn more","Illegal to discard in garbage. Ask your contractor to recycle, look for retail or wholesale drop-offs, or take to household special waste drop-off site or upcoming DSNY SAFE disposal event.","thermostats (mercury),mercury thermostats,mercury devices,mercury containing devices,thermostat"];
dispose_data[163] = ["tire (auto)","/assets/dsny/zerowaste/residents/tires.shtml","learn more","When buying new tires, bring back your old ones to be recycled. NYC residents can drop off up to four passenger car tires at a DSNY garage during certain times.","tire (auto),car,tire,car tire,auto tire,waste tire,automotive,automotive tire,tires,car tires,automotive tires,auto tires"];
dispose_data[164] = ["tire (bicycle)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Discard as garbage on your regular collection day(s).","tire (bicycle),tire,bike tire,bike tires,inner tube,inner tubes,bicycle tire,bicycle tires,bike inner tube,bicycle inner tube"];
dispose_data[165] = ["toothbrush (rigid plastic)","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Recycle with metal, glass, plastic & cartons.","toothbrush"];
dispose_data[166] = ["toothbrush (electric)","/assets/dsny/zerowaste/residents/batteries.shtml","learn more","Bring item to any store that sells this product so rechargeable battery can be properly discarded. NY State's Rechargeable Battery mandates that stores that sell rechargeable batteries (or products containing rechargeable batteries) must take back up to ten batteries of the same shape and size as they sell, free of charge.","electric toothbrush"];
dispose_data[167] = ["toy (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/childrens-items.shtml","learn more","Donate or sell if in good condition (certain restrictions apply). Otherwise recycle with metal, glass, plastic & cartons. Be sure to remove batteries before placing in recycling bin.","toy (mostly metal or rigid plastic),metal,toy,toys,wagon,plastic toys,"];
dispose_data[168] = ["toy (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/childrens-items.shtml","learn more","Donate or sell if in good condition (certain restrictions apply). Otherwise discard as garbage on your regular collection day(s).","toy (not mostly metal or rigid plastic),wood toys"];
dispose_data[169] = ["TVs and peripherals","/assets/dsny/zerowaste/residents/electronics.shtml","learn more","Donate or sell if in working condition. Otherwise recycle through a legally-mandated free take-back program for TVs, VCRs, DVRs, DVD/Blu-Ray players, cable or satellite receivers, and video game consoles. Can be taken to upcoming DSNY SAFE disposal events. It is illegal to place electronic waste in the garbage.","TVs and peripherals,electronics,electronic,audio/visual equipment,A/V equipment,vcr,digital video recorder,digital video recorders,dvr,dvd players,blu-ray players,digital converter boxes,cable box,cable receiver,satellite box,satellite boxes,satellite receiver,satellite receivers,electronic game console,video game console,T.V.,Television,Televisions,TV,console tv,CRT,CRTs,cathode ray tube,cathode ray tubes,lcd,plasma,led tv,led tvs"];
dispose_data[170] = ["umbrellas","/assets/dsny/zerowaste/residents/non-recyclable-plastics.shtml","learn more","These items are problematic to recycle, do not place in recycling bin. Discard as garbage on your regular collection day(s).","umbrella,umbrellas"];
dispose_data[171] = ["unwanted medication","/assets/dsny/zerowaste/residents/household-medical-waste.shtml","learn more","Participate in periodic collection events, or use mailback envelope sold at many pharmacies. Otherwise, most should be mixed with a material like coffee grounds or kitty litter, put in nondescript container marked \"not recyclable - disposal only,\" and discarded as regular garbage. If instructed to do so on the label, certain medications should be flushed for safety purposes.","unwanted medication,unwanted medications,drugs,medicine (drugs) ,pill,pills,syrup,prescription,prescriptions,Rx,medication,over-the-counter,pharmaceuticals,controlled substances,medicine bottle (not empty),pill bottle (not empty)"];
dispose_data[172] = ["vehicle","/assets/dsny/about/laws/vehicle-and-bike-laws.shtml","learn more","Donate vehicles; report abandoned vehicles.","vehicle,vehicles,car,cars,truck,trucks,auto,derelict vehicles,abandoned vehicle,abandoned vehicles,abandonded,motorcycle,boat,boats"];
dispose_data[173] = ["wagon/cart (mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Donate or sell if in good condition. Otherwise set out next to your recycling container on your recycling collection day.","wagon/cart (mostly metal or rigid plastic),wagon,wagons,cart,carts"];
dispose_data[174] = ["wagon/cart (not mostly metal or rigid plastic)","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Donate or sell if in good condition. Otherwise, discard as garbage on your regular collection day(s).","wagon/cart (not mostly metal or rigid plastic),wagon,cart"];
dispose_data[175] = ["water bottle","/assets/dsny/zerowaste/residents/deposit-bottles.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic & cartons, or return to store for refund.","water bottle,water bottles,plastic water bottle,plastic water bottles,deposit bottle/can,deposit container,deposit containers,deposit bottle,deposit can,deposit bottles,deposit cans"];
dispose_data[176] = ["wax or plastic coated paper","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","These items are problematic to recycle; do not place in recycling bin. Discard as garbage on your regular collection day(s). Lightly waxed or plastic-coated paper, such as magazines or cereal and toothpaste boxes can be recycled.","non-recyclable paper,takeout container (waxed paper),take-out container (waxed paper),chinese takeout container,chinese take-out container,gum wrapper,gum wrappers,hot chocolate wrapper,photographic paper,ice cream containers,ice cream tubs,waxed paper,plastic coated paper"];
dispose_data[177] = ["wine bottle","/assets/dsny/zerowaste/residents/what-to-recycle-for-residents.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic, & cartons.","wine bottle,wine bottles,champaign bottle,champagne bottle,champaign bottles,champagne bottles"];
dispose_data[178] = ["wine cooler","/assets/dsny/zerowaste/residents/deposit-bottles.shtml","learn more","Empty & rinse. Recycle with metal, glass, plastic & cartons, or return to store for refund.","wine cooler,deposit bottle/can,deposit container,deposit containers,deposit bottle,deposit can,deposit bottles,deposit cans"];
dispose_data[179] = ["wreath","/assets/dsny/zerowaste/residents/curbside-setout-for-residents.shtml","learn more","Because wreaths contain wire, they can't be composted and should be discarded as bulk garbage on your regular collection day(s).","wreath,wreaths"];

# Sample Data:
# [0](title) - antifreeze
# [1](url) - /assets/dsny/zerowaste/residents/antifreeze.shtml
# [2](link text) - learn more
# [3](summary) - Never drain antifreeze onto the street, and do not dispose down the drain, in sewers, or into streams. Have your antifreeze changed by a professional who offers recycling. Antifreeze can also be taken to upcoming DSNY SAFE disposal events. Otherwise, dry out antifreeze using kitty litter, newspaper, or other absorbent material prior to discarding in the garbage. Empty antifreeze containers can be recycled with other metal, glass, plastic & cartons.
# [4](synonyms) - antifreeze,coolant

class RecycleItem():
	def __init__( self, title, url, moreLinkText, summary, terms ):
		self.title = title
		self.url = url
		self.localUrl = 'html/'+re.sub('/.*/','',self.url).replace('.shtml','.html')
		self.moreLinkText = moreLinkText
		self.summary = summary
		self.terms = terms

	def sectionHtmlTemplate( self ):
		return '''
		<div class="list-entry">
			<div class="title">
				<h1><i class="dropdown icon"></i><span class="listjs-title">%s</span></h1>
				<p class="summary" style="font-weight: normal;"><b>Summary: </b>%s</p>
				<div class="listjs-tags" style="font-weight: normal; opacity: 0.5">%s</div>
			</div>
			<div class="content">%%s</div>
		</div>
		'''.replace('\n\t\t','\n').strip('\n') % (
			self.title.title(),
			self.summary,
			', '.join(self.terms)
		)

# Reads the downloaded data and creates an html group for each section.
# The section includes meta-data and other info. They all are combined
# and written to an output file: dump.
if __name__ == '__main__':

	recycleItems = []
	for data in dispose_data:
		recycleItems.append( RecycleItem(
			data[0],
			data[1],
			data[2],
			data[3],
			[ x.strip(' ') for x in data[4].split(',') ]
		) )

	sections = []
	for item in recycleItems:
		try:
			with open( item.localUrl ) as f:
				sections.append( item.sectionHtmlTemplate() % f.read() )
		except IOError:
			sections.append( item.sectionHtmlTemplate() % 'No extra info' )

	with open( 'template.html' ) as f:
		template = f.read()

	with open( 'index.html', 'w' ) as f:
		f.write( template % '\n\n'.join( sections ) )
	
	# Clean up
	'''
	import os
	import shutil
	os.remove( 'out.html' )
	shutil.rmtree( 'html' )
	shutil.rmtree( 'html_raw' )
	'''
